services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    image: softvence/lawalbackendbackend:latest
    profiles:
      - prod
    container_name: lawalbackendbackend3
    restart: always
    env_file:
      - .env
      - .env.production
    depends_on:
      - db
      - redis
    volumes:
      - uploads:/app/uploads
      - uploads-file:/app/uploads-file
      - uploads-profile-images:/app/uploads-profile-images
    ports:
      - 2342:2342
    networks:
      - law_network

  db:
    image: postgres:15
    container_name: law_db
    restart: always
    profiles:
      - prod
      - dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - law_pgdata:/var/lib/postgresql/data
    networks:
      - law_network

  redis:
    image: redis:7
    container_name: law_redis_cache
    restart: always
    profiles:
      - prod
      - dev
    volumes:
      - law_redisdata:/data
    networks:
      - law_network

volumes:
  law_pgdata:
  law_redisdata:
  uploads-profile-images:
  uploads-file:
  uploads:

networks:
  law_network:
    driver: bridge
