services:
  db:
    image: postgres:15
    container_name: law_db
    ports:
      - '5435:5432' # Maps Host 5434 -> Container 5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      # Use /data, not /new, so Postgres initializes the DB properly
      - law_pgdata_new:/var/lib/postgresql/data 
    networks:
      - law_network

  redis:
    image: redis:7
    container_name: law_redis_cache
    ports:
      - '6382:6379'
    volumes:
      - law_redisdata:/data
    networks:
      - law_network

volumes:
  law_pgdata_new:
  law_redisdata:

networks:
  law_network:
    driver: bridge
