

services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis_cache:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6380:6379"
    volumes:
      - redisdata:/data

  nest-app:
    image: sakibsakib/lawex:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-app
    restart: always
    depends_on:
      - postgres_db
      - redis_cache
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres_db:5432/appdb?schema=public"
      REDIS_HOST: "redis_cache"
      REDIS_PORT: "6379"
      REDIS_CONNECTION_URL: "redis://redis_cache:6379"
      NODE_ENV: development
    ports:
      - "5000:5000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

  prisma_studio:
    image: node:20
    container_name: prisma_studio
    working_dir: /usr/src/app
    command: sh -c "npx prisma generate && npx prisma studio --port 5555"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres_db:5432/appdb?schema=public"
    ports:
      - "5566:5555"
    volumes:
      - ./prisma:/usr/src/app/prisma
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
    user: "node"
    depends_on:
      - postgres_db
      - nest-app

volumes:
  pgdata:
  redisdata:
