services:
  postgres_db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  redis_cache:
    image: redis/redis-stack:latest
    container_name: redis_cache
    restart: always
    ports:
      - '6379:6379'
    networks:
      - app_network

  # nest-app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     args:
  #       NODE_ENV: ${NODE_ENV:-development}
  #   container_name: nest-app
  #   env_file:
  #     - .env
  #   environment:
  #     NODE_ENV: ${NODE_ENV:-development}
  #   depends_on:
  #     - postgres_db
  #     - redis_cache
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   restart: always
  #   networks:
  #     - app_network

  # ------------------------
  # Prisma Studio
  # ------------------------
  # prisma_studio:
  # image: node:18-alpine
  # container_name: prisma_studio
  # working_dir: /usr/src/app
  # volumes:
  #   - .:/usr/src/app
  # command: sh -c "npx prisma generate && npx prisma studio"
  # depends_on:
  #   - postgres_db
  # ports:
  #   - "5555:5555"
  # env_file:
  #   - .env
  # networks:
  #   - app_network
  # restart: always

# ------------------------
# Volumes and Networks
# ------------------------
volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
